name: DEPLOY_STAGING
on:
  push:
    branches:
      - devops/deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: ls -la
      - run: cd app && npm install && npm run build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: app/dist/
          remote_path: ${{ secrets.DEPLOYMENT_PATH }}
          remote_host: ${{ secrets.DEPLOYMENT_SERVER_STAGING }}
          remote_user: ${{ secrets.DEPLOYMENT_USER }}
          remote_key: ${{ secrets.DEPLOYMENT_KEY }}
